import React from "react"
import CustomTable from "../../../components/Table/CustomTable"
import {Link} from "react-router-dom"
import {
    acosColumn,
    adCvrColumn,
    adOrdersColumn, adProfitColumn, adSalesColumn, adSalesOtherSKUColumn, adSalesSameSKUColumn,
    adSpendColumn, adUnitsColumn, budgetAllocationColumn,
    clicksColumn, cpaColumn, cpcColumn, CPMColumn,
    ctrColumn, ICVRColumn,
    impressionsColumn, roasColumn, RPCColumn, RPIColumn, salesShareColumn,
    statusColumn
} from "../../AnalyticsV3/components/TableList/tableColumns"
import {currencyWithCode} from "../../../components/CurrencyCode/CurrencyCode"
import {round} from "../../../utils/round"
import moment from "moment-timezone"
import {activeTimezone} from "../../index"

const columns = [
    {
        title: 'Campaign',
        dataIndex: 'name',
        key: 'name',
        width: '350px',
    },
    statusColumn,
    {
        title: 'Advertising Type',
        dataIndex: 'advertisingType',
        key: 'advertisingType',
        width: '170px',
        render: (type) => type && type.replace(/([a-z])([A-Z])/g, '$1 $2')
    },
    {
        title: 'Targeting Type',
        dataIndex: 'calculatedTargetingType',
        key: 'calculatedTargetingType',
        width: '160px',
        render: (type) => type && <span className={'camelcase-string'}>{type} Targeting</span>
    },
    {
        title: 'Sub Type',
        dataIndex: 'calculatedCampaignSubType',
        key: 'calculatedCampaignSubType',
        width: '150px',
        render: (type) => type && type.replace(/([a-z])([A-Z])/g, '$1 $2')
    },
    {
        title: 'Budget',
        dataIndex: 'calculatedBudget',
        key: 'calculatedBudget',
        width: '140px',
        render: (budget, item) => {
            const text = budget ? <>{currencyWithCode(round(budget, 2))} {item.calculatedBudgetType ? ` / ${item.calculatedBudgetType}` : ''}</> : ''
            return <span className={'overflow-text campaign-budget'} title={text}>{text}</span>
        }
    },
    {
        title: 'Portfolio',
        dataIndex: 'portfolioName',
        key: 'portfolioName',
        width: '150px',
    },
    {
        title: 'Start date',
        dataIndex: 'startDate',
        key: 'startDate',
        width: '150px',
        render: (date) => date && moment(date).format('DD.MM.YYYY'),
    },
    {
        title: 'End date',
        dataIndex: 'endDate',
        key: 'endDate',
        width: '150px',
        render: (date) => date && moment(date).format('DD.MM.YYYY'),
    },
    {
        title: 'Campaign bidding strategy',
        dataIndex: 'bidding_strategy',
        key: 'bidding_strategy',
        width: '250px',
        render: (text) => <>
            {text === 'legacyForSales' && 'Legacy For Sales'}
            {text === 'autoForSales' && 'Auto For Sales'}
            {text === 'manual' && 'Manual'}
            {(text !== 'manual' && text !== 'autoForSales' && text !== 'legacyForSales') && text}
        </>
    },
    impressionsColumn,
    clicksColumn,
    ctrColumn,
    adSpendColumn,
    cpcColumn,
    CPMColumn,
    budgetAllocationColumn,
    adOrdersColumn,
    cpaColumn,
    adCvrColumn,
    ICVRColumn,
    adUnitsColumn,
    adSalesColumn,
    acosColumn,
    roasColumn,
    RPCColumn,
    RPIColumn,
    adSalesSameSKUColumn,
    adSalesOtherSKUColumn,
    salesShareColumn,
    adProfitColumn,
]

const fakeData = [
    {
        "campaignId": "47764621",
        "name": "campaign 1 SKU-5567",
        "state": "enabled",
        "advertisingType": "SponsoredProducts",
        "targetingType": "manual",
        "bidding_strategy": "manual",
        "startDate": "20220210",
        "endDate": "20230623",
        "calculatedTargetingType": "manual",
        "calculatedBudget": null,
        "calculatedBudgetType": "daily",
        "calculatedCampaignSubType": "Manual",
        "portfolioId": "55786231765664",
        "portfolioName": "portfolio SKU-5567",
        "impressions": 0,
        "clicks": 0,
        "cost": 0,
        "attributedSales": 0,
        "attributedSalesSameSKU": 0,
        "attributedSalesOtherSKU": 0,
        "attributedConversions": 0,
        "attributedUnitsOrdered": 0,
        "ad_profit": 0,
        "ctr": null,
        "cpc": null,
        "acos": null,
        "roas": null,
        "conversion_rate": null,
        "cpa": null,
        "cpm": null,
        "icvr": null,
        "rpc": null,
        "rpi": null,
        "budget_allocation": null,
        "sales_share": null
    }, {
        "campaignId": "243033549",
        "name": "campaign 4 SKU-12",
        "state": "enabled",
        "advertisingType": "SponsoredProducts",
        "targetingType": "manual",
        "bidding_strategy": "manual",
        "startDate": "20220210",
        "endDate": "20230818",
        "calculatedTargetingType": "manual",
        "calculatedBudget": null,
        "calculatedBudgetType": "daily",
        "calculatedCampaignSubType": "Manual",
        "portfolioId": "39442171253635",
        "portfolioName": "portfolio SKU-12",
        "impressions": 0,
        "clicks": 0,
        "cost": 0,
        "attributedSales": 0,
        "attributedSalesSameSKU": 0,
        "attributedSalesOtherSKU": 0,
        "attributedConversions": 0,
        "attributedUnitsOrdered": 0,
        "ad_profit": 0,
        "ctr": null,
        "cpc": null,
        "acos": null,
        "roas": null,
        "conversion_rate": null,
        "cpa": null,
        "cpm": null,
        "icvr": null,
        "rpc": null,
        "rpi": null,
        "budget_allocation": null,
        "sales_share": null
    }, {
        "campaignId": "321647881",
        "name": "campaign 4 SKU-5578",
        "state": "enabled",
        "advertisingType": "SponsoredProducts",
        "targetingType": "manual",
        "bidding_strategy": "manual",
        "startDate": "20220210",
        "endDate": "20230623",
        "calculatedTargetingType": "manual",
        "calculatedBudget": null,
        "calculatedBudgetType": "daily",
        "calculatedCampaignSubType": "Manual",
        "portfolioId": "6122403089806",
        "portfolioName": "portfolio SKU-5578",
        "impressions": 0,
        "clicks": 0,
        "cost": 0,
        "attributedSales": 0,
        "attributedSalesSameSKU": 0,
        "attributedSalesOtherSKU": 0,
        "attributedConversions": 0,
        "attributedUnitsOrdered": 0,
        "ad_profit": 0,
        "ctr": null,
        "cpc": null,
        "acos": null,
        "roas": null,
        "conversion_rate": null,
        "cpa": null,
        "cpm": null,
        "icvr": null,
        "rpc": null,
        "rpi": null,
        "budget_allocation": null,
        "sales_share": null
    }, {
        "campaignId": "429344440",
        "name": "campaign 4 SKU-5564",
        "state": "enabled",
        "advertisingType": "SponsoredProducts",
        "targetingType": "manual",
        "bidding_strategy": "manual",
        "startDate": "20220210",
        "endDate": "20230523",
        "calculatedTargetingType": "manual",
        "calculatedBudget": null,
        "calculatedBudgetType": "daily",
        "calculatedCampaignSubType": "Manual",
        "portfolioId": "10908379237091",
        "portfolioName": "portfolio SKU-5564",
        "impressions": 0,
        "clicks": 0,
        "cost": 0,
        "attributedSales": 0,
        "attributedSalesSameSKU": 0,
        "attributedSalesOtherSKU": 0,
        "attributedConversions": 0,
        "attributedUnitsOrdered": 0,
        "ad_profit": 0,
        "ctr": null,
        "cpc": null,
        "acos": null,
        "roas": null,
        "conversion_rate": null,
        "cpa": null,
        "cpm": null,
        "icvr": null,
        "rpc": null,
        "rpi": null,
        "budget_allocation": null,
        "sales_share": null
    }, {
        "campaignId": "659403226",
        "name": "campaign 5 SKU-5563",
        "state": "enabled",
        "advertisingType": "SponsoredProducts",
        "targetingType": "manual",
        "bidding_strategy": "manual",
        "startDate": "20220210",
        "endDate": "20240113",
        "calculatedTargetingType": "manual",
        "calculatedBudget": null,
        "calculatedBudgetType": "daily",
        "calculatedCampaignSubType": "Manual",
        "portfolioId": "97087006040655",
        "portfolioName": "portfolio SKU-5563",
        "impressions": 0,
        "clicks": 0,
        "cost": 0,
        "attributedSales": 0,
        "attributedSalesSameSKU": 0,
        "attributedSalesOtherSKU": 0,
        "attributedConversions": 0,
        "attributedUnitsOrdered": 0,
        "ad_profit": 0,
        "ctr": null,
        "cpc": null,
        "acos": null,
        "roas": null,
        "conversion_rate": null,
        "cpa": null,
        "cpm": null,
        "icvr": null,
        "rpc": null,
        "rpi": null,
        "budget_allocation": null,
        "sales_share": null
    }, {
        "campaignId": "700311201",
        "name": "campaign 4 SKU-5545",
        "state": "enabled",
        "advertisingType": "SponsoredProducts",
        "targetingType": "manual",
        "bidding_strategy": "manual",
        "startDate": "20220210",
        "endDate": "20230303",
        "calculatedTargetingType": "manual",
        "calculatedBudget": null,
        "calculatedBudgetType": "daily",
        "calculatedCampaignSubType": "Manual",
        "portfolioId": "66371950817387",
        "portfolioName": "portfolio SKU-5545",
        "impressions": 0,
        "clicks": 0,
        "cost": 0,
        "attributedSales": 0,
        "attributedSalesSameSKU": 0,
        "attributedSalesOtherSKU": 0,
        "attributedConversions": 0,
        "attributedUnitsOrdered": 0,
        "ad_profit": 0,
        "ctr": null,
        "cpc": null,
        "acos": null,
        "roas": null,
        "conversion_rate": null,
        "cpa": null,
        "cpm": null,
        "icvr": null,
        "rpc": null,
        "rpi": null,
        "budget_allocation": null,
        "sales_share": null
    }, {
        "campaignId": "1055205615",
        "name": "campaign 3 SKU-35",
        "state": "enabled",
        "advertisingType": "SponsoredProducts",
        "targetingType": "manual",
        "bidding_strategy": "manual",
        "startDate": "20220210",
        "endDate": "20230212",
        "calculatedTargetingType": "manual",
        "calculatedBudget": null,
        "calculatedBudgetType": "daily",
        "calculatedCampaignSubType": "Manual",
        "portfolioId": "29606841908283",
        "portfolioName": "portfolio SKU-35",
        "impressions": 0,
        "clicks": 0,
        "cost": 0,
        "attributedSales": 0,
        "attributedSalesSameSKU": 0,
        "attributedSalesOtherSKU": 0,
        "attributedConversions": 0,
        "attributedUnitsOrdered": 0,
        "ad_profit": 0,
        "ctr": null,
        "cpc": null,
        "acos": null,
        "roas": null,
        "conversion_rate": null,
        "cpa": null,
        "cpm": null,
        "icvr": null,
        "rpc": null,
        "rpi": null,
        "budget_allocation": null,
        "sales_share": null
    }, {
        "campaignId": "1258249247",
        "name": "campaign 5 SKU-5560",
        "state": "enabled",
        "advertisingType": "SponsoredProducts",
        "targetingType": "manual",
        "bidding_strategy": "manual",
        "startDate": "20220210",
        "endDate": "20231220",
        "calculatedTargetingType": "manual",
        "calculatedBudget": null,
        "calculatedBudgetType": "daily",
        "calculatedCampaignSubType": "Manual",
        "portfolioId": "1194989500188",
        "portfolioName": "portfolio SKU-5560",
        "impressions": 0,
        "clicks": 0,
        "cost": 0,
        "attributedSales": 0,
        "attributedSalesSameSKU": 0,
        "attributedSalesOtherSKU": 0,
        "attributedConversions": 0,
        "attributedUnitsOrdered": 0,
        "ad_profit": 0,
        "ctr": null,
        "cpc": null,
        "acos": null,
        "roas": null,
        "conversion_rate": null,
        "cpa": null,
        "cpm": null,
        "icvr": null,
        "rpc": null,
        "rpi": null,
        "budget_allocation": null,
        "sales_share": null
    }, {
        "campaignId": "1378008872",
        "name": "campaign 1 SKU-5569",
        "state": "enabled",
        "advertisingType": "SponsoredProducts",
        "targetingType": "manual",
        "bidding_strategy": "manual",
        "startDate": "20220210",
        "endDate": "20230224",
        "calculatedTargetingType": "manual",
        "calculatedBudget": null,
        "calculatedBudgetType": "daily",
        "calculatedCampaignSubType": "Manual",
        "portfolioId": "75471065569223",
        "portfolioName": "portfolio SKU-5569",
        "impressions": 0,
        "clicks": 0,
        "cost": 0,
        "attributedSales": 0,
        "attributedSalesSameSKU": 0,
        "attributedSalesOtherSKU": 0,
        "attributedConversions": 0,
        "attributedUnitsOrdered": 0,
        "ad_profit": 0,
        "ctr": null,
        "cpc": null,
        "acos": null,
        "roas": null,
        "conversion_rate": null,
        "cpa": null,
        "cpm": null,
        "icvr": null,
        "rpc": null,
        "rpi": null,
        "budget_allocation": null,
        "sales_share": null
    }, {
        "campaignId": "1601573002",
        "name": "campaign 5 SKU-5518",
        "state": "enabled",
        "advertisingType": "SponsoredProducts",
        "targetingType": "manual",
        "bidding_strategy": "manual",
        "startDate": "20220210",
        "endDate": "20231118",
        "calculatedTargetingType": "manual",
        "calculatedBudget": null,
        "calculatedBudgetType": "daily",
        "calculatedCampaignSubType": "Manual",
        "portfolioId": "96592351773567",
        "portfolioName": "portfolio SKU-5518",
        "impressions": 0,
        "clicks": 0,
        "cost": 0,
        "attributedSales": 0,
        "attributedSalesSameSKU": 0,
        "attributedSalesOtherSKU": 0,
        "attributedConversions": 0,
        "attributedUnitsOrdered": 0,
        "ad_profit": 0,
        "ctr": null,
        "cpc": null,
        "acos": null,
        "roas": null,
        "conversion_rate": null,
        "cpa": null,
        "cpm": null,
        "icvr": null,
        "rpc": null,
        "rpi": null,
        "budget_allocation": null,
        "sales_share": null
    }]


export const TopCampaigns = ({
                                 fetching,
                                 data
                             }) => {


    return (<div className="table-block">
        <CustomTable
            loading={fetching}
            dataSource={fakeData}

            columns={columns}

            fixedColumns={[0]}
        />
    </div>)
}