//--------------------------------------------
//------------ user constants-----------------
//--------------------------------------------
export const userConstants = {
    SET_INFORMATION: 'SET_INFORMATION',
    UPDATE_USER: 'UPDATE_USER',
    UNSET_AMAZON_MWS: 'UNSET_AMAZON_MWS',
    UNSET_AMAZON_PPC: 'UNSET_AMAZON_PPC',
    SET_PPC_STATUS: 'SET_PPC_STATUS',
    SET_AMAZON_REGION_ACCOUNTS: 'SET_AMAZON_REGION_ACCOUNTS',
    SET_ACTIVE_REGION: 'SET_ACTIVE_REGION',
    UPDATE_AMAZON_REGION_ACCOUNTS: 'UPDATE_AMAZON_REGION_ACCOUNTS',
    SET_NOTIFICATIONS: 'SET_NOTIFICATIONS',
    ACTUALIZE_ACTIVE_REGION: 'ACTUALIZE_ACTIVE_REGION',
}

//--------------------------------------------
//------------ product constants--------------
//--------------------------------------------
export const productsConstants = {
    SET_PRODUCT_LIST: 'SET_PRODUCT_LIST',
    UPDATE_PRODUCT_OPTIONS: 'UPDATE_PRODUCT_OPTIONS',
    SELECT_PRODUCT: 'SELECT_PRODUCT',
    UPDATE_SELECTED_PRODUCT: 'UPDATE_SELECTED_PRODUCT',
    SELECT_ALL_PRODUCT: 'SELECT_ALL_PRODUCT',
    SHOW_ONLY_OPTIMIZED: 'SHOW_ONLY_OPTIMIZED',
    SHOW_ONLY_ON_DAYPARTING: 'SHOW_ONLY_ON_DAYPARTING',
    SHOW_ONLY_ACTIVE: 'SHOW_ONLY_ACTIVE',
    CHANGE_OPTIONS: 'CHANGE_OPTIONS',
    CHANGE_STRATEGY: 'CHANGE_STRATEGY',
    SWITCH_START_CONFIRM_WINDOW: 'SWITCH_START_CONFIRM_WINDOW',
    SWITCH_STOP_CONFIRM_WINDOW: 'SWITCH_STOP_CONFIRM_WINDOW',
    CAMPAIGN_BUDGET: 'CAMPAIGN_BUDGET',
    SET_FETCHING_STATE: 'SET_FETCHING_STATE',
    CHANGE_OPTIMIZATION_STATUS: 'CHANGE_OPTIMIZATION_STATUS',
}

//--------------------------------------------
//------------ reports constants--------------
//--------------------------------------------
export const reportsConstants = {
    SET_REPORTS_LIST: 'SET_REPORTS_LIST',
    START_FETCH_REPORTS_LIST: 'START_FETCH_REPORTS_LIST',
    SET_PAGE_SIZE: 'SET_PAGE_SIZE',
}

//--------------------------------------------
//------------ dashboard constants--------------
//--------------------------------------------
export const dashboardConstants = {
    SWITCH_DAILY_CHART: 'SWITCH_DAILY_CHART',
    SWITCH_WEEK_CHART: 'SWITCH_WEEK_CHART',
    SWITCH_OPTIMIZATION_CHART: 'SWITCH_OPTIMIZATION_CHART',
    REMOVE_SELECTED_METRIC: 'REMOVE_SELECTED_METRIC',
    UPDATE_METRICS_LIST: 'UPDATE_METRICS_LIST',
    ACTIVATE_METRIC: 'ACTIVATE_METRIC',
    DEACTIVATE_METRIC: 'DEACTIVATE_METRIC',
    SELECTED_RANGE_DATE: 'SELECTED_RANGE_DATE',
    SET_METRICS_STATISTIC: 'SET_METRICS_STATISTIC',
    SELECT_PRODUCT: 'SELECT_PRODUCT_ON_DASHBOARD',
    RE_SET: 'RE_SET',
    SET_PRODUCTS_MARGIN_STATUS: 'SET_PRODUCTS_MARGIN_STATUS',
    RELOAD_METRICS: 'RELOAD_METRICS',
    SET_ADVERTISING_TYPE: 'SET_ADVERTISING_TYPE',
}

//--------------------------------------------
//------------ dayparting constants--------------
//--------------------------------------------
export const daypartingConstants = {
    SET_CAMPAIGN_LIST: 'SET_CAMPAIGN_LIST',
    SET_PROCESSING_STATE: 'SET_PROCESSING_STATE',
    SELECT_CAMPAIGN: 'SELECT_CAMPAIGN',
    ACTIVATED_DAYPARTING: 'ACTIVATED_DAYPARTING',
    DEACTIVATED_DAYPARTING: 'DEACTIVATED_DAYPARTING',
    COPY_PARAMS: 'COPY_PARAMS',
}

//--------------------------------------------
//---------- zero to hero constants-----------
//--------------------------------------------
export const zthConstants = {
    SET_CAMPAIGN: 'SET_CAMPAIGN',
    SET_PRODUCT_AMOUNT: 'SET_PRODUCT_AMOUNT',
    ADD_PRODUCTS: 'ADD_PRODUCTS',
    REMOVE_PRODUCTS: 'REMOVE_PRODUCTS',
    SET_ACTIVE_PRODUCT: 'SET_ACTIVE_PRODUCT',
    UPDATE_ACTIVE_PRODUCT: 'UPDATE_ACTIVE_PRODUCT',
    SET_INVALID_FIELD: 'SET_INVALID_FIELD',
    SET_PAID_BATCH: 'SET_PAID_BATCH',
    CLEAR_SETTINGS: 'CLEAR_SETTINGS',
}

//--------------------------------------------
//---------- analytics constants-----------
//--------------------------------------------
export const analyticsConstants = {
    SET_MAIN_STATE: 'SET_MAIN_STATE',
    SET_CHART_STATE: 'SET_CHART_STATE',
    SET_DATE_RANGE: 'SET_DATE_RANGE',
    SET_LOCATION: 'SET_LOCATION',
    UPDATE_METRICS_STATE: 'UPDATE_METRICS_STATE',
    UPDATE_METRICS_DATA: 'UPDATE_METRICS_DATA',
    SET_COLUMNS_BLACK_LIST: 'SET_COLUMNS_BLACK_LIST',
    SET_FILTERS_LIST: 'SET_FILTERS_LIST',
    SET_METRICS_DATA: 'SET_METRICS_DATA',
    SET_CHART_VIEW: 'SET_CHART_VIEW',
    SET_WORKPLACE_VIEW: 'SET_WORKPLACE_VIEW',
    SET_SEGMENT_VALUE: 'SET_SEGMENT_VALUE',
    SET_STATE_DETAILS: 'SET_STATE_DETAILS',
    SET_SORTING_COLUMN: 'SET_SORTING_COLUMN',
    SET_VISIBLE_CREATION_WINDOWS: 'SET_VISIBLE_CREATION_WINDOWS',
    SET_PORTFOLIOS: 'SET_PORTFOLIOS',
    SET_ATTRIBUTION_WINDOW: 'SET_ATTRIBUTION_WINDOW',
}
