export const userTypeEnums = {
    'ADMIN': 'USER_TYPE_ADMIN',
    'ADVANCED_CLIENT': 'USER_TYPE_ADVANCED_CLIENT',
    'AGENCY_CLIENT': 'USER_TYPE_AGENCY_CLIENT',
    'SAAS_CLIENT': 'USER_TYPE_SAAS_CLIENT'
}